version: '3.8'

services:
  gcs-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached
    
    ports:
      - "5010:5010"
      - "5173:5173" 
      - "8080:8080" 

    command: sleep infinity